### ISSUE TITLE
feign.FeignException$NotFound: status 404 reading ItemService#queryItemById(Long)

### ISSUE THREAD

**Issue by wecloud2008** [OpenFeign/feign#1059]
eign.FeignException$NotFound: status 404 reading ItemService#queryItemById(Long) at feign.FeignException.errorStatus(FeignException.java:98) ~[feign-core-10.2.3.jar:na] at feign.FeignException.errorStatus(FeignException.java:86) ~[feign-core-10.2.3.jar:na] at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:93) ~[feign-core-10.2.3.jar:na] at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:149) ~[feign-core-10.2.3.jar:na] at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78) ~[feign-core-10.2.3.jar:na]

application.yml
spring:
application:
name: microsns-order
eureka:
client:
server-url:
defaultZone: http://localhost:8761/eureka
register-with-eureka: false
fetch-registry: true
server:
port: 8082
feign:
hystrix:
enabled: false

`package com.chtrak.microsns.microsnsorder.service;

import com.chtrak.microsns.microsnsorder.entity.Item;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.cloud.openfeign.FeignClient;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestTemplate;

@FeignClient("microscs-item")
public interface ItemService {

@RequestMapping(value = "/item/{id}",method = RequestMethod.GET)
Item queryItemById(@PathVariable("id") Long id);
}

**Comment by wecloud2008** [comment]
server.port=8081

Closed
