### ISSUE TITLE
Calling FeignException.getContentUTF8() can throw NPE

### ISSUE THREAD

**Issue by jcvillalta03** [OpenFeign/feign#1099]
If the exception, does not have a `content` byte array initialized, calling `getContentUTF8()` will throw an exception, because the String initializer (below) does not accept a null `byte[]`  

Method referred above:
```  
public String contentUTF8() {
    return new String(content, UTF_8);
  }
```
StackTrace: 
```Failure in @ExceptionHandler public final org.springframework.http.ResponseEntity<com.dais.common.feign.FeignErrorResponse> com.example.feign.FeignExceptionHandler.handleFeignException(feign.FeignException,org.springframework.web.context.request.WebRequest)
java.lang.NullPointerException: null
        at java.lang.String.<init>(String.java:515)
        at feign.FeignException.contentUTF8(FeignException.java:57)
        at com.dais.common.feign.FeignExceptionHandler.handleFeignException(FeignExceptionHandler.kt:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver.doResolveHandlerMethodException(ExceptionHandlerExceptionResolver.java:408)
        at org.springframework.web.servlet.handler.AbstractHandlerMethodExceptionResolver.doResolveException(AbstractHandlerMethodExceptionResolver.java:61)
```

I can create PR with fix

**Comment by jcvillalta03** [comment]
Looks like I was pulling down an older version of the library, and it has been patched already. Apologies for raising the issue
