### ISSUE TITLE
what anotation sholud use for Request.Options for timeout controling?

### ISSUE THREAD

**Issue by zzsoszz** [OpenFeign/feign#1103]
interface define blew:
```java
    @RequestLine("POST /kunlun-kiosk-new/rest/gje/checkIn")
    @Headers({"Content-Type: application/json", "Accept: application/json","Authorization: Bearer {token}"})
    CheckInResponse checkIn(@Param("token") String token, CheckInRequest checkInRequest, Request.Options options);
```

error blow:
```java

java.lang.IllegalStateException: Method has too many Body parameters: public abstract com.veryqy.hotelclient.opera.model.CheckInResponse com.veryqy.hotelclient.opera.OperaInterface.checkIn(java.lang.String,com.veryqy.hotelclient.opera.model.CheckInRequest,feign.Request$Options)

	at feign.Util.checkState(Util.java:128)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:114)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53)
	at feign.Feign$Builder.target(Feign.java:198)
	at feign.Feign$Builder.target(Feign.java:194)
	at com.veryqy.hotelclient.opera.OperaClient.<init>(OperaClient.java:81)
	at com.veryqy.HotelInterfaceManager.getInterfaceById(HotelInterfaceManager.java:27)
	at com.veryqy.ClientTest.init(ClientTest.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by velo** [comment]
Hey,

This is only available on newer version of feign. Try it on 10.6 all lemme know how it goes.

**Comment by kdavisk6** [comment]
Given the time passed here, I'm going to assume that the issue is resolved.
