### ISSUE TITLE
feign will throw NullPointerException  if params is not key-value data structure

### ISSUE THREAD

**Issue by 77yang** [OpenFeign/feign#1135]
`@RequestLine("POST /{index}/_delete_by_query?conflicts=proceed&refresh&slices=5")
    @Headers({"Accept: application/json", "Content-Type: application/json"})
    String deleteByQuery(@Param("index") String index, String body);`

if refresh doesn't have value,  feign will throw NullPointerException, if I let refresh=true, feign will works
`Exception in thread "main" java.lang.NullPointerException
	at feign.RequestTemplate.replaceQueryValues(RequestTemplate.java:683)
	at feign.RequestTemplate.resolve(RequestTemplate.java:224)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.resolve(ReflectiveFeign.java:327)
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:385)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:222)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:101)
	at com.sun.proxy.$Proxy22.deleteByQuery(Unknown Source)
	at com.expedia.www.vector.alert.client.MonitoringElasticsearchClient.deleteByQuery(MonitoringElasticsearchClient.java:177)`

feign-core-version 10.0.1

**Comment by kdavisk6** [comment]
I recommend using the latest version of Feign and see if your issue is resolved.  There have been numerous advances and changes since 10.0.1 and there is a strong possibility that this issue has been fixed.

**Comment by 77yang** [comment]
@kdavisk6 okay, thanks for your feedback

**Comment by raerocole-patientping** [comment]
@77yang Did using the latest version of feign end up fixing your issue?
