### ISSUE TITLE
Sending "{}" as header value fails since 10.2.0

### ISSUE THREAD

**Issue by neiser** [OpenFeign/feign#1172]
The following minimal reproducer in https://github.com/neiser/feign-reproduce-empty-json-header-value-bug using the code

```java
    public static void main(String[] args) {
        TestClient testClient = Feign.builder().target(TestClient.class, "http://google.com");
        testClient.get(""); // works!
        testClient.get("{\"a\":  \"b\"}"); // works!
        testClient.get("{}"); // fails!
    }


    private interface TestClient {
        @Headers({
            "Some-Header-Key: {someHeaderValue}"
        })
        @RequestLine("GET /")
        void get(@Param("someHeaderValue") String someHeaderValue);
    }
```

shows that sending the string `{}` as a header value fails with 

```
Exception in thread "main" java.lang.IllegalArgumentException: an expression is required.
	at feign.template.Expressions.create(Expressions.java:48)
	at feign.template.Template.parseFragment(Template.java:194)
	at feign.template.Template.parseTemplate(Template.java:178)
	at feign.template.Template.<init>(Template.java:60)
	at feign.template.HeaderTemplate.<init>(HeaderTemplate.java:81)
	at feign.template.HeaderTemplate.create(HeaderTemplate.java:57)
	at feign.RequestTemplate.lambda$appendHeader$3(RequestTemplate.java:742)
	at java.util.Map.compute(Map.java:1093)
	at feign.RequestTemplate.appendHeader(RequestTemplate.java:740)
	at feign.RequestTemplate.header(RequestTemplate.java:710)
	at feign.RequestTemplate.header(RequestTemplate.java:692)
	at feign.RequestTemplate.resolve(RequestTemplate.java:236)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.resolve(ReflectiveFeign.java:328)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:232)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:75)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at $Proxy4.get(Unknown Source)
	at Main.main(Main.java:12)
```

This bug still appears in version 10.7.4 and is failing since version 10.2.0. In 10.0.1, the above code works.

**Comment by kdavisk6** [comment]
@neiser 

Empty expressions are not allowed in `@Param` or `@HeaderParam` annotations.  In your example, the resulting expression will be `{{}}` which is invalid, hence the exception.  You must either escape the values or provide them as pct-encoded.

**Comment by neiser** [comment]
@kdavisk6 Thanks for your reply. I don't quite get your point though. In the example above, I'm using the expression `Some-Header-Key: {someHeaderValue}` which has the non-empty template variable `{someHeaderValue}`, which I want to substitute with the **value** `{}`. It's just a value, and should not be interpreted as an expression IMHO. 

Also, if I read the RFC concerning the allowed HTTP Header values, I think a header such as:
```
Some-Header-Key: {}
```
should be ok (and was actually working before version 10.2.0).

Can you adapt my above example to show me how I'm supposed to use it?

**Comment by neiser** [comment]
@kdavisk6 I tooke the freedom to offer a PR to with a proposed fix, see #1195

**Comment by kdavisk6** [comment]
@neiser 

Let me look into the Header Template again.  It should not be processing it twice as you've alluded to in your PR.

**Comment by kdavisk6** [comment]
I've reviewed the code and this will take some refactoring to address.  I am going to mark this as a bug and reserve time to work through it.

**Comment by neiser** [comment]
@kdavisk6 Thanks for investigating this! If you'd lay down how you'd like to see it fixed, I could try and make another PR? Or do you want to work on it on your own?

**Comment by neiser** [comment]
@kdavisk6 Thanks for fixing it. Any chance to get Feign released with this bug fix soon?

**Comment by kdavisk6** [comment]
I need to fix a release issue regarding our java 11 binaries.  Once that is corrected, this will go out.
