### ISSUE TITLE
@QueryMap too long value will appear 414?

### ISSUE THREAD

**Issue by longbig** [OpenFeign/feign#1232]
if I put a very long value into queryMap, the feign get request will occur FeignException 414. This is my interface code:

```java
@RequestLine("GET {path}")
@Headers("Content-Type: application/json;charset=UTF-8")
String getWithQueryMap(@Param("path") String path, @QueryMap Map<String, Object> queryMap) throws Exception;

```

And this is the queryMap parameters:

```java
String ids = "11036439,11037130......";  //about 400 id
Map<String, Object> queryMap = Maps.newHashMap();
queryMap.put("ids", ids);
```

And this is the exception

```java
feign.FeignException: status 414 reading FeignUtilsClient#getWithQueryMap(String,Map)
	at feign.FeignException.errorStatus(FeignException.java:124)
	at feign.FeignException.errorStatus(FeignException.java:86)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:93)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:149)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy275.getWithQueryMap(Unknown Source)
	at com.longbig.utils.HttpClientUtils.getWithMap(HttpClientUtils.java:414)
	at com.longbig.utils.HttpsTest.test1(HttpsTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
......
```

I don't know how to fix it, does anyone know this problem ?

**Comment by longbig** [comment]
I have fix the problem，use @Param instead of @QueryMap

```java
@RequestLine("GET {path}?ids={ids}")
@Headers("Content-Type: application/json;charset=UTF-8")
String getWithQueryMap1(@Param("path") String path, @Param("ids") String ids) throws Exception;
```

**Comment by finnetrolle** [comment]
Hi longbig. I think this is not feign-side issue. You've received[ 414 code that means you've sent too big query](https://httpstatuses.com/414#:~:text=414%20Request%2DURI%20Too%20Long,server%20is%20willing%20to%20interpret.). Also can be found [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.15).
In fact HTTP 1.1 protocol allow any length of query but different servers accept different max length.

So to avoid that issue you need not to do something to feign but try other options such as:
1) Use POST instead of GET
2) Split one big array to several small GET queries.

**Comment by longbig** [comment]
> Hi longbig. I think this is not feign-side issue. You've received[ 414 code that means you've sent too big query](https://httpstatuses.com/414#:~:text=414%20Request%2DURI%20Too%20Long,server%20is%20willing%20to%20interpret.). Also can be found [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.15).
> In fact HTTP 1.1 protocol allow any length of query but different servers accept different max length.
> 
> So to avoid that issue you need not to do something to feign but try other options such as:
> 
> 1. Use POST instead of GET
> 2. Split one big array to several small GET queries.

Thank you, I had resolved the problem by split the parameters finally
