### ISSUE TITLE
AsyncFeign java.net.SocketException

### ISSUE THREAD

**Issue by mason6345** [OpenFeign/feign#1289]
Doing a performance test for my service that uses AsyncFeign (the default client).

I see this frequently, though it occurs in a minority of the http requests.

```
java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at feign.Client$Default.convertResponse(Client.java:108)
	at feign.Client$Default.execute(Client.java:104)
	at feign.AsyncClient$Default.lambda$execute$0(AsyncClient.java:60)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kdavisk6** [comment]
This is from the underlying HTTP client and the connection to the server.  From the exception it appears that the server didn't complete the data transfer.  I recommend looking into your server more.  If you are able to create a minimal reproducible example, please feel free to re-open this issue and we will work with you solve it.
