### ISSUE TITLE
Incompatibility with Android's JRE (10, not tested others)

### ISSUE THREAD

**Issue by xrpdevs** [OpenFeign/feign#1433]
Hi, I've been trying to get to the bottom of this problem and have been lead here through debugging steps.

I have a library which uses OKHttp3 and thus OpenFeign.

If I compile an example command line java app with OpenFeign dependencies using mvn compile, I get no issues using the computer's JRE, but when I import the libraries into Android Studio, my project builds OK, but I get an exception related to the IMPL_LOOKUP field being missing or inaccessible.

I'm using  implementation 'io.github.openfeign:feign-core:11.2'
and implementation 'io.github.openfeign:feign-jackson:11.2'

The error stack trace relating to OpenFeign is below:

`No field IMPL_LOOKUP in class Ljava/lang/invoke/MethodHandles$Lookup; (declaration of 'java.lang.invoke.MethodHandles$Lookup' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at feign.DefaultMethodHandler.legacyReadLookup(DefaultMethodHandler.java:83)
        at feign.DefaultMethodHandler.readLookup(DefaultMethodHandler.java:55)
        at feign.DefaultMethodHandler.<init>(DefaultMethodHandler.java:41)
        at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:57) 
        at feign.Feign$Builder.target(Feign.java:269) 
        at feign.Feign$Builder.target(Feign.java:265) 
        at org.xrpl.xrpl4j.client.JsonRpcClient.construct(JsonRpcClient.java:60) 
        at org.xrpl.xrpl4j.client.XrplClient.<init>(XrplClient.java:92) 
        at uk.co.xrpdevs.flarenetmessenger.MyService.onCreate(MyService.java:136) 
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3981) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1900) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7386) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) `

Would be most appreciative if anybody is able to shed any light on this!

Regards

Jamie

**Comment by xrpdevs** [comment]
Running the same code on Android 8 produces the following:

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.xrpdevs.xrp4jtest, PID: 7494
    java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.co.xrpdevs.xrp4jtest/uk.co.xrpdevs.xrp4jtest.MainActivity}: java.lang.IllegalStateException: java.lang.IllegalAccessException: no private access for invokespecial : interface org.xrpl.xrpl4j.client.JsonRpcClient, fromjava.lang.Object
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalStateException: java.lang.IllegalAccessException: no private access for invokespecial : interface org.xrpl.xrpl4j.client.JsonRpcClient, fromjava.lang.Object
        at feign.DefaultMethodHandler.<init>(DefaultMethodHandler.java:45)
        at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:57)
        at feign.Feign$Builder.target(Feign.java:269)
        at feign.Feign$Builder.target(Feign.java:265)
        at org.xrpl.xrpl4j.client.JsonRpcClient.construct(JsonRpcClient.java:60)
        at org.xrpl.xrpl4j.client.XrplClient.<init>(XrplClient.java:92)
        at uk.co.xrpdevs.xrp4jtest.MainActivity.onCreate(MainActivity.java:22)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.IllegalAccessException: no private access for invokespecial : interface org.xrpl.xrpl4j.client.JsonRpcClient, fromjava.lang.Object
        at java.lang.invoke.MethodHandles$Lookup.checkSpecialCaller(MethodHandles.java:1661)
        at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1453)
        at feign.DefaultMethodHandler.<init>(DefaultMethodHandler.java:42)
        at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:57) 
        at feign.Feign$Builder.target(Feign.java:269) 
        at feign.Feign$Builder.target(Feign.java:265) 
        at org.xrpl.xrpl4j.client.JsonRpcClient.construct(JsonRpcClient.java:60) 
        at org.xrpl.xrpl4j.client.XrplClient.<init>(XrplClient.java:92) 
        at uk.co.xrpdevs.xrp4jtest.MainActivity.onCreate(MainActivity.java:22) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
`

**Comment by xrpdevs** [comment]
Managed to fix this and have submitted a PR.

**Comment by kdavisk6** [comment]
Addressed in 11.3
