### ISSUE TITLE
feign.FeignException$Forbidden: [403 Forbidden] encountered when running on Java 8?

### ISSUE THREAD

**Issue by PLT875** [OpenFeign/feign#1563]
No issue on Java 11

Feign core version is feign-core:11.7

Encountered the error when running on Java 8. Is Java  not fully supported: https://github.com/OpenFeign/feign#java-version-compatibility

`
  at feign.FeignException.clientErrorStatus(FeignException.java:217) ~[feign-core-11.7.jar:na]
        at feign.FeignException.errorStatus(FeignException.java:194) ~[feign-core-11.7.jar:na]
        at feign.FeignException.errorStatus(FeignException.java:185) ~[feign-core-11.7.jar:na]
        at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-11.7.jar:na]
        at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[feign-core-11.7.jar:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-11.7.jar:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-11.7.jar:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-11.7.jar:na]
`

**Comment by kdavisk6** [comment]
This is probably related to the `Client` you are using.  The result being logged is what the `Client` returned.  I recommend trying to isolate what's happening in the request handling.
