### ISSUE TITLE
Java 11 HTTP client incorrectly reports 'invalid URI' exception message when cause is thread interruption

### ISSUE THREAD

**Issue by Col-E** [OpenFeign/feign#2188]
Offending line: https://github.com/OpenFeign/feign/blob/master/java11/src/main/java/feign/http2client/Http2Client.java#L102

Example stacktrace:
```
 Caused by: java.io.IOException: Invalid uri https://yourdomainhere.com/api/example?foo=bar
 	at feign.http2client.Http2Client.execute(Http2Client.java:102) ~[feign-java11-12.5.jar!/:?]
 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:100) ~[feign-core-12.5.jar!/:?]
 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-12.5.jar!/:?]
 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:96) ~[feign-core-12.5.jar!/:?]
 	... 9 more
 Caused by: java.lang.InterruptedException
 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386) ~[?:?]
 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
 	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:553) ~[java.net.http:?]
 	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
 	at feign.http2client.Http2Client.execute(Http2Client.java:99) ~[feign-java11-12.5.jar!/:?]
 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:100) ~[feign-core-12.5.jar!/:?]
 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70) ~[feign-core-12.5.jar!/:?]
```

Its minor, but rather annoying when the error logs going by message alone are misleading.

**Comment by velo** [comment]
Ow, feels like a copy&paste bug.

Feel free to send a PR our way.
