### ISSUE TITLE
after upgrade version from springboot 3.1.6 to 3.2.0 can not start

### ISSUE THREAD

**Issue by jinyulei0710** [OpenFeign/feign#2257]
Caused by: java.lang.IllegalStateException: Method OssApi#getDetail(String) not annotated with HTTP method type (ex. GET, POST)
Warnings:
Warnings:
- Class OssApi has annotations [FeignClient] that are not used by contract Default
- Method getDetail has an annotation GetMapping that is not used by contract Default
	at feign.Util.checkState(Util.java:140)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:115)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:65)
	at feign.DeclarativeContract.parseAndValidateMetadata(DeclarativeContract.java:38)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:137)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:56)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:48)
	at feign.Feign$Builder.target(Feign.java:201)
	at org.springframework.cloud.openfeign.DefaultTargeter.target(DefaultTargeter.java:30)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:399)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:447)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:422)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:182)
	... 57 common frames omitted

do not make any change only the dependency bump to 3.2.0 and 2023.0.0

**Comment by peakshaofeng233** [comment]
Me too.

**Comment by kdavisk6** [comment]
This is a SpringCloud Annotation issue.  Please use their support channels for this.  `@GetMapping` is not a core Feign annotation.
