### ISSUE TITLE
Header issue: feign.RetryableException

### ISSUE THREAD

**Issue by jaylucas** [OpenFeign/feign#413]
I am trying to add multiple headers while still requiring params for a get request but feign doesn't like it.

    @Headers({
             "Authorization: {auth}",
            "X-API-Key: {key}"
     })
     @RequestLine("GET /api/path/{variable}")
      public String foo(@Param("auth") String auth,
                                           @Param("key") String key,
                                           @Param("variable") String variable);`

Resulting in:
`feign.RetryableException: handshake alert:  unrecognized_name executing GET xxxxx/api/path/test`

I feel like it has something to do with header params. I have also tried:

    @RequestLine("GET /api/path/{variable}")
    public String foo(@Named("auth") String auth,
                                           @Named("key") String key,
                                           @Param("variable") String variable);`

Which didnt work. All named didnt work either.
And I am getting this in the stacktrace:

    
	at feign.FeignException.errorExecuting(FeignException.java:66)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:100)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
	at com.sun.proxy.$Proxy32.verifyDomainRegistration(Unknown Source)
        ....
    Caused by: javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
	at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1441)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2016)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at feign.Client$Default.convertResponse(Client.java:150)
	at feign.Client$Default.execute(Client.java:72)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:95)

**Comment by adriancole** [comment]
I don't think we designed this with collaboration in mind.. Do you need the
caller to provide the first value explicity (vs a Target or interceptor)?

**Comment by jaylucas** [comment]
`Auth` and `X-API-Key` is retrieved at runtime (only required once at startup) not once per call. I would love any advice or example code to to show me how that could be done.

**Comment by adriancole** [comment]
you could do it as a custom target 

https://github.com/Netflix/denominator/blob/master/dynect/src/main/java/denominator/dynect/DynECTTarget.java

`builder.target(new YourCustomTarget(...))`

or as an interceptor like basic auth
https://github.com/Netflix/feign/blob/master/core/src/main/java/feign/auth/BasicAuthRequestInterceptor.java

`builder.requestInterceptor(yourCustomInterceptor)...`

**Comment by adriancole** [comment]
target is guaranteed to be the last to affect the request, and a bit more explicit
