### ISSUE TITLE
Getting "EOFException: Unexpected EOF read on the socket" in tomcat by using Feign

### ISSUE THREAD

**Issue by wanghongfei** [OpenFeign/feign#454]
I use Feign as HTTP client to send request to my tomcat server. But I got following message for nearly every request in tomcat's console output:

```
2016-09-05 10:53:15 [DEBUG] o.a.coyote.http11.Http11NioProcessor - Error parsing HTTP request header
java.io.EOFException: Unexpected EOF read on the socket
    at org.apache.coyote.http11.InternalNioInputBuffer.fill(InternalNioInputBuffer.java:152) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
    at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:190) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) ~[tomcat-embed-core-8.0.33.jar:8.0.33]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.33.jar:8.0.33]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) [tomcat-embed-core-8.0.33.jar:8.0.33]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) [tomcat-embed-core-8.0.33.jar:8.0.33]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.33.jar:8.0.33]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

I'm a little worried about this exception(performance impact because tomcat keeps throwing exception).

I'm using Feign in Spring Cloud Brixton.SR5. By the way, this problem was solved when I use Apache Http Client instead of Feign's native httpclient

**Comment by kdavisk6** [comment]
@wanghongfei Thanks for the input.  I know it's been a few years, but if you have an example test that can recreate the issue, it would be helpful for others.

**Comment by wanghongfei** [comment]
@kdavisk6 Thanks for your replay. Due to the years has being passed,  we have already upgraded to Edgware version and there's no reason to go back to the old version. I' closing this case, thanks!
