### ISSUE TITLE
'HTTP 204 No Content' response results in java.io.EOFException in feign.slf4j.Slf4jLogger

### ISSUE THREAD

**Issue by maximdim** [OpenFeign/feign#462]
REST DELETE call defined in Feign client as follows:

```
@RequestLine("DELETE /students/{id}")
void deleteStudent(@Param("id") String id);
```

Server returns "HTTP 204 No Content" which results in exception:

```
---> DELETE https://test.foo/students/f26f3612-3660-427c-a8b5-dc428de17df0
<--- HTTP/1.1 204 No Content (240ms)
cache-control: no-cache
content-type: application/json
date: Mon, 19 Sep 2016 17:14:26 GMT
expires: -1
okhttp-received-millis: 1474305275717
okhttp-sent-millis: 1474305275468
pragma: no-cache
request-id: 1836d724-f62b-4773-90d9-3c78c24f4adf
server: Microsoft-IIS/8.5
x-aspnet-version: 4.0.30319
x-powered-by: ASP.NET

<--- ERROR EOFException: null (240ms)
java.io.EOFException
    at okio.RealBufferedSource.require(RealBufferedSource.java:64)
    at okio.GzipSource.consumeHeader(GzipSource.java:114)
    at okio.GzipSource.read(GzipSource.java:73)
    at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
    at java.io.InputStream.read(InputStream.java:101)
    at feign.Util.copy(Util.java:307)
    at feign.Util.toByteArray(Util.java:290)
    at feign.Logger.logAndRebufferResponse(Logger.java:96)
    at feign.slf4j.Slf4jLogger.logAndRebufferResponse(Slf4jLogger.java:62)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:112)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
    at com.sun.proxy.$Proxy13.deleteStudent(Unknown Source)
    at Client.deleteStudent(IsusClient2.java:318)
```

**Comment by maximdim** [comment]
Feign version 9.3.1
