### ISSUE TITLE
How to handle api endpoint that contains <index.php?> ?

### ISSUE THREAD

**Issue by MolineroUA** [OpenFeign/feign#530]
I want to write a feign client for TestRail api, and according to documentation http://docs.gurock.com/testrail-api2/start and discussion with support team the endpoints must contain index.php? in the url.

But, when I try to use 
> @RequestMapping(method = GET, value = 'index.php?/api/v2/get_run/{runId}')

an exception appears
> java.lang.IllegalStateException: Body parameters cannot be used with form parameters.
	at feign.Util.checkState(Util.java:128)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:112)
	at org.springframework.cloud.netflix.feign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:133)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53)
	at feign.Feign$Builder.target(Feign.java:198)
	at feign.Feign$Builder.target(Feign.java:194)
	at feign.Feign$Builder$target$5.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)

As I understand the issue is related to symbol '?' in url.
Is it possible to handle this issue?

**Comment by CoufalJa** [comment]
Hi,

based on the code I think you are using a wrong annotation there.
You are using RequestMapping which is probably the Spring MVC one instead of RequestLine annotation from Feign.

**Comment by CoufalJa** [comment]
Sorry I missed the org.springframework.cloud.netflix.feign.support.SpringMvcContract line in stacktrace. Then you probably need to reach Spring Cloud guys as this is their extension.

**Comment by vasilievip** [comment]
There is some spring related code in example, but you can employ RequestInterceptor to rewrite request url

```

import feign.RequestInterceptor;
import feign.RequestTemplate;
import org.springframework.util.ReflectionUtils;

import static java.util.Optional.ofNullable;
import static org.springframework.util.ReflectionUtils.findField;

...

TestRailFeignClient:

    @PostMapping(value = "/index.php/api/v2/update_case/{caseId}")
    void updateCase(@PathVariable("caseId") String caseId,
                                      @RequestBody UpdateCaseRequest request);

...

TestRailFeignClientContext:

       @Bean
        public RequestInterceptor fixGovnoApiInterceptor() {
            return requestTemplate -> {
                String url = requestTemplate.url();
                if (url.contains("index.php/api/v2")) {
                    url = url.replace("index.php/", "index.php?/");
                    Optional<Field> field = ofNullable(findField(RequestTemplate.class, "url"));
                    if (field.isPresent()) {
                        ReflectionUtils.makeAccessible(field.get());
                        ReflectionUtils.setField(field.get(), requestTemplate, new StringBuilder(url));
                    }
                }
            };
        }
...
```

**Comment by MolineroUA** [comment]
@vasilievip 
thank you, it works for me
