### ISSUE TITLE
how to use annotation to send multi object paramters ?

### ISSUE THREAD

**Issue by HongKing** [OpenFeign/feign#629]
I want use feign and springmvc controller like this:
```
@RequestMapping(value = "/save")
String saveUser(@RequestJson(value = "user") User user, @RequestJson(value = "group") Group group);
```
feign build this param to request body like this:
```
{
  'user':{'name':......},
  'group':{'name':.....}
}
```
in springmvc controller we can write a resolver class to parse this request body, but I don't known how to build this param to request body. 

In springmvc I parse this request body code as follows:
```
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface RequestJson {
    
    /**
     * bind paramter name
     */
    String value() default "";
    
    boolean required() default true;
}
```
```
public class RequestJsonMethodProcessor implements HandlerMethodArgumentResolver {

    @Override
    public boolean supportsParameter(MethodParameter parameter) {
        return parameter.hasParameterAnnotation(RequestJson.class);
    }

    @Override
    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
            NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {
        
        HttpServletRequest request = webRequest.getNativeRequest(HttpServletRequest.class);
        JSONObject json = (JSONObject) request.getSession().getAttribute("TEMP_JSON_BODY");
        if (json == null) {
            json = getJsonFromBody(request);
            request.getSession().setAttribute("TEMP_JSON_BODY", json); // cache request body content to session
            // in global interceptor.preHandle() session.removeAttribute("TEMP_JSON_BODY")
        }
        mavContainer.setRequestHandled(true);
        
        parameter = parameter.nestedIfOptional();
        Type targetType = parameter.getNestedGenericParameterType();
        Class<?> targetClass = (targetType instanceof Class ? (Class<?>) targetType : null);
        RequestJson aa = parameter.getParameterAnnotation(RequestJson.class);
        JSONObject a = json.getJSONObject(aa.value());

        return JSONObject.toBean(a, targetClass);
    }
    
    private JSONObject getJsonFromBody(HttpServletRequest request) {
        StringBuffer sb = new StringBuffer();
        String line = null;
        try {
            BufferedReader reader = request.getReader();
            while ((line = reader.readLine()) != null) {
                sb.append(line);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return JSONObject.fromObject(sb.toString());
    }
    
}
```
```
@Configuration
@EnableWebMvc
public class WebConfig extends WebMvcConfigurerAdapter {
      @Override
      public void addArgumentResolvers(List<HandlerMethodArgumentResolver> argumentResolvers) {
          argumentResolvers.add(new RequestJsonMethodProcessor());
      }
}
```

**Comment by benmanbs** [comment]
I believe you can accomplish this with a custom [Encoder](https://github.com/OpenFeign/feign#encoders).

**Comment by orwashere** [comment]
Alternatively you could use a wrapper object and use it as the post body. So you can define a class like
```
public class UserGroupWrapper {
    private User user;
    private Group group;
    //getters/setters omitted
}
```
and than pass it to your post method like 
```
@PostMapping("/save")
String saveUser(UserGroupWrapper wrapper);
```

**Comment by HongKing** [comment]
@orwashere ，I know this can solve the problem, but it will define more than one class. There are many objects in the actual project, it will define many unnecessary classes.

**Comment by HongKing** [comment]
@benmanbs  the Encoder `@Body` can combine several simple parameters into JSON

```
@Body("%7B\"user_name\": \"{user_name}\", \"password\": \"{password}\"%7D")
void json(@Param("user_name") String user, @Param("password") String password);
```
But when the parameters are complex objects, it wile throw excetion
```
@Body("%7B\"user\": \"{user}\", \"group\": \"{group}\"%7D")
String saveUser22(User user, Group group);
```
```
Caused by: java.lang.IllegalStateException: Method has too many Body parameters: 
	at feign.Util.checkState(Util.java:128)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:114)
....
```

**Comment by rage-shadowman** [comment]
Would using a custom expander work?
```java
void json(@Param(value = "user", expander = JsonTextExpander.class) User user,
@Param(value = "group", expander = JsonTextExpander.class) Group group);
```
Your `JsonTextExpander` would implement `feign.Param.Expander` which would take an `Object` and use Jackson (or whatever) to turn the object into a `String` and return that.

**Comment by HongKing** [comment]
@rage-shadowman TKS, it's good idea. ^_^

**Comment by always-young** [comment]
> @rage-shadowman TKS, it's good idea. ^_^

hello , do you resolve this problem in the end？
