### ISSUE TITLE
Allow empty @Path annotation in JAXRSContract?

### ISSUE THREAD

**Issue by iamdanfox** [OpenFeign/feign#630]
Currently, I'm unable to connect to a server using the following interface:

```java
@Path("") // empty string causes 🔥🔥🔥 
public interface NoSlashService {
    @GET
    @Path("/foo")
    @Produces(MediaType.APPLICATION_JSON)
    Map<String, Integer> foo();
}
```

Given that jetty/jersey seem to be able to serve this happily, would it be possible to relax the validation error from `JAXRSContract`, possibly turning it into a warning?

```
java.lang.IllegalStateException: Path.value() was empty on type com.something.demo.NoSlashService
	at feign.Util.checkState(Util.java:128)
	at feign.jaxrs.JAXRSContract.processAnnotationOnClass(JAXRSContract.java:58)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:91)
	at feign.jaxrs.JAXRSContract.parseAndValidateMetadata(JAXRSContract.java:50)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
```

I know there's an easy workaround, just move the slash to the top (below).  Just curious whether feign is unnecessarily banning a technically valid configuration!

```java
@Path("/")
public interface NoSlashService {
    @GET
    @Path("foo")
    @Produces(MediaType.APPLICATION_JSON)
    Map<String, Integer> foo();
}
```

**Comment by kdavisk6** [comment]
Addressed by #631
