### ISSUE TITLE
The ClassCastException for org.springframework.http.HttpHeaders instance in feign.Contract

### ISSUE THREAD

**Issue by Alykoff** [OpenFeign/feign#655]
Hello,
I updated my project to `Spring Boot 2`. `Feign` library was migrated from version `9.5.0` to `9.5.1` in `Spring Boot 2`. And now my `feign` version is `9.5.1` and my spring boot app failed.

I'm using `org.springframework.http.HttpHeaders` class and have `ClassCastException`. 
If change `HttpHeaders` to `java.util.Map` everything is ok.

Stacktrace:
```
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at feign.Contract$BaseContract.checkMapString(Contract.java:137) ~[feign-core-9.5.1.jar:na]
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:124) ~[feign-core-9.5.1.jar:na]
	at org.springframework.cloud.openfeign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:133) ~[spring-cloud-openfeign-core-2.0.0.M1.jar:2.0.0.M1]
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:66) ~[feign-core-9.5.1.jar:na]
	at feign.hystrix.HystrixDelegatingContract.parseAndValidatateMetadata(HystrixDelegatingContract.java:34) ~[feign-hystrix-9.5.1.jar:na]
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146) ~[feign-core-9.5.1.jar:na]
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53) ~[feign-core-9.5.1.jar:na]
	at feign.Feign$Builder.target(Feign.java:218) ~[feign-core-9.5.1.jar:na]
```

The problem appeared from that commit https://github.com/OpenFeign/feign/commit/a029afd8666b9a8ddeaecd1599e10b7b55f43bb4
```java
feign.Contract.java:
// 137 line
Type[] parameterTypes = ((ParameterizedType) genericType).getActualTypeArguments();
```

My app:
```java
public interface GraphQLClient {
    @RequestMapping(value = "/graphql/d", method = RequestMethod.POST)
    ExecutionResultWrapper execute(@RequestBody QueryWrapper queryWrapper, @RequestHeader HttpHeaders httpHeaders);
}
```

```java
import own.DefaultFeignConfiguration;
import own.CustomErrorDecoder;
import feign.Client;
import feign.Target;
import feign.hystrix.HystrixFeign;
import feign.slf4j.Slf4jLogger;
import org.springframework.beans.factory.ObjectFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.http.HttpMessageConverters;
import org.springframework.cloud.netflix.ribbon.SpringClientFactory;
import org.springframework.cloud.openfeign.ribbon.CachingSpringLoadBalancerFactory;
import org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient;
import org.springframework.cloud.openfeign.support.ResponseEntityDecoder;
import org.springframework.cloud.openfeign.support.SpringDecoder;
import org.springframework.cloud.openfeign.support.SpringEncoder;
import org.springframework.cloud.openfeign.support.SpringMvcContract;
import org.springframework.stereotype.Component;

@Component
public class ClientBuilder {
    // ...
    public <T> T buildClient(Class<T> targetInterface, String prefix, String url) {
        Target<T> custom = new Target.HardCodedTarget<>(targetInterface, url, prefix + url);
        T target = HystrixFeign.builder()
                .contract(new SpringMvcContract())
                .options(feignConfig.options())
                .logger(new Slf4jLogger())
                .logLevel(feignConfig.level())
                .client(
                        new LoadBalancerFeignClient
                                (new Client.Default(null, null), cachingFactory, clientFactory)
                )
                .decoder(new ResponseEntityDecoder(new SpringDecoder(messageConverters)))
                .encoder(new SpringEncoder(messageConverters))
                .errorDecoder(customErrorDecoder)
                .target(custom); // failed in this method
        return target;
    }
}
```

**Comment by kdavisk6** [comment]
This appears to be an issue with the `SpringMvcContract` as that object is responsible for translating the Spring `HttpHeaders` object into the appropriate Feign object.  I would open this issue with Spring Cloud.

**Comment by hopperd** [comment]
This doesn't appear to be an issue with `SpringMvcContract`, as it delegates down to `super` for the validation which is in `Contract` specifically [here](https://github.com/OpenFeign/feign/commit/a029afd8666b9a8ddeaecd1599e10b7b55f43bb4#diff-da4026da682060a1cec91cd10354f9e9R137).

If I downgrade just feign to 9.5.0 this error goes away.

**Comment by kdavisk6** [comment]
Looking at the changes in Feign, it expects the parameters to be a `Map` but also expose the `key` and `value` types.  It appears that Spring's `HttpHeaders` does not return the types expected when calling `getActualTypeArguments`.  I'll see if I can run some tests later on and verify.

**Comment by kdavisk6** [comment]
I figured out the issue and submitted a PR.

**Comment by hopperd** [comment]
Nicely done @kdavisk6
