### ISSUE TITLE
feign-ribbon dependency of ribbon is 2.1.1, but this some error.

### ISSUE THREAD

**Issue by YangGuang001** [OpenFeign/feign#657]
```java
Caused by: java.lang.IllegalAccessError: tried to access method com.netflix.config.DynamicIntProperty.<init>(Ljava/lang/String;I)V from class com.netflix.loadbalancer.DynamicServerListLoadBalancer
	at com.netflix.loadbalancer.DynamicServerListLoadBalancer.<clinit>(DynamicServerListLoadBalancer.java:86)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.netflix.client.ClientFactory.instantiateInstanceWithClientConfig(ClientFactory.java:202)
	at com.netflix.client.ClientFactory.registerNamedLoadBalancerFromclientConfig(ClientFactory.java:166)
	at com.netflix.client.ClientFactory.registerNamedLoadBalancerFromProperties(ClientFactory.java:187)
```
but in springcloud version, this was use ribbin 2.2.0, it was ok

**Comment by YangGuang001** [comment]
MyService api = Feign.builder().client(RibbonClient.create()).target(MyService.class, "https://myAppProd");

**Comment by YangGuang001** [comment]
```java
public DynamicIntProperty(String propName, int defaultValue) {
        super(propName, Integer.valueOf(defaultValue));
    }
```
should be
```java
public DynamicIntProperty(String propName, int defaultValue) {
        public super(propName, Integer.valueOf(defaultValue));
    }
```
