### ISSUE TITLE
@QueryMap not working with POJOs as specified in documentation

### ISSUE THREAD

**Issue by doublemc** [OpenFeign/feign#691]
According to: https://github.com/OpenFeign/feign#dynamic-query-parameters it should be possible to write:
`@RequestLine("GET /api/v1/historicalTrades")
    fun getHistoricalTrades(@QueryMap orderBookQuery: OrderBookQuery): List<TradeEntry>`

where OrderBookQuery looks like that: 
`data class OrderBookQuery(val symbol: String, val limit: Int? = 100)`

Feign should generate: `/api/v1/historicalTrades?symbol={symobl}&limit={limit}` but I'm getting:
`Exception in thread "main" java.lang.IllegalStateException: QueryMap parameter must be a Map: class com.binance.api.feign.marketdata.model.OrderBookQuery
	at feign.Util.checkState(Util.java:128)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:126)
	at feign.Contract$BaseContract.parseAndValidatateMetadata(Contract.java:64)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:146)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:53)
	at feign.Feign$Builder.target(Feign.java:198)
	at feign.Feign$Builder.target(Feign.java:194)`

Here is my config and usage that produces above exception:
` val marketDataRestClient =
        Feign.builder().encoder(GsonEncoder())
            .decoder(GsonDecoder())
            .logger(Logger.ErrorLogger())
            .logLevel(Logger.Level.FULL)
            .target(MarketDataRestClient::class.java, "https://api.binance.com")

    val s = marketDataRestClient.getHistoricalTrades(OrderBookQuery("ETHBTC"))`

Link to my SO if someone wants to get them free karma points ;) : https://stackoverflow.com/questions/50044283/feign-querymap-usage-with-pojo

**Comment by kdavisk6** [comment]
I don't believe this feature is available in the released versions.  It's been accepted to `master` and will be part of 9.7.  If you want to use this now, you will need to build the library from `master`.

**Comment by doublemc** [comment]
DO you know when 9.7 is going live?

**Comment by velo** [comment]
I think, by the end of the week

**Comment by kdavisk6** [comment]
9.7 was released.

**Comment by kdavisk6** [comment]
@doublemc Are you still experiencing this issue with 9.7?

**Comment by 3p5i10n** [comment]
Bug is still present, neither 9.7 nor 10.0.1 solve the Issue.

`java.lang.IllegalStateException: QueryMap parameter must be a Map: class org.foo.QueryParameters`

No CustomEncoder is used, as mentioned in the docs.

`@RequestLine("GET /v1/foo/")
public Foo getFoo(@QueryMap QueryParameters queryParameters);
`

**Comment by rage-shadowman** [comment]
Do you have a small failing test case example?

**Comment by 3p5i10n** [comment]
While trying to reproduce it again in a separate sample project, i was not able to.
Now 9.7 and 10.0.1 are working fine ...have to check my base project again.

Sorry for the inconvenience and the late response, been busy the last weeks.
