### ISSUE TITLE
NPE on `RequestTemplate`

### ISSUE THREAD

**Issue by velo** [OpenFeign/feign#820]
While testing `10.1` release #818 found an NPE on `RequestTemplate`

```
Stacktrace was: java.lang.NullPointerException
	at feign.template.UriUtils.urlEncode(UriUtils.java:121)
	at feign.template.UriUtils.encodeChunk(UriUtils.java:217)
	at feign.template.UriUtils.encodeReserved(UriUtils.java:156)
	at feign.template.UriUtils.pathEncode(UriUtils.java:88)
	at feign.template.Template.encode(Template.java:121)
	at feign.template.Template.parseFragment(Template.java:210)
	at feign.template.Template.parseTemplate(Template.java:183)
	at feign.template.Template.<init>(Template.java:60)
	at feign.template.UriTemplate.<init>(UriTemplate.java:73)
	at feign.template.UriTemplate.create(UriTemplate.java:50)
	at feign.RequestTemplate.uri(RequestTemplate.java:444)
	at feign.RequestTemplate.uri(RequestTemplate.java:402)
	at feign.RequestTemplate.resolve(RequestTemplate.java:206)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.resolve(ReflectiveFeign.java:319)
	at feign.ReflectiveFeign$BuildEncodedTemplateFromArgs.resolve(ReflectiveFeign.java:377)
	at feign.ReflectiveFeign$BuildTemplateByResolvingArgs.create(ReflectiveFeign.java:223)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:102)
```

It only happens with `binary` body.

Example unit test available here: https://github.com/OpenFeign/feign/pull/821/files

**Comment by velo** [comment]
@kdavisk6 I think I will need a hand on this one.

I think we need 2 different encondings.... one that is exclusive for body and another one that is for everything else?!

What do you think?

**Comment by kdavisk6** [comment]
The exception is due to the charset being null. Was that just the start of the issue?  Is there something else I may be missing?

**Comment by velo** [comment]
> The exception is due to the charset being null
yes. I saw this one a custom encode we use at work, that produces a binary format.  Documentation somewhere said to set charset to null and setting it to anything different from null lead to client enconding my binary payload, which corrupts the whole thing.

**Comment by velo** [comment]
> The exception is due to the charset being null
yes. I saw this one a custom encode we use at work, that produces a binary format.  Documentation somewhere said to set charset to null and setting it to anything different from null lead to client enconding my binary payload, which corrupts the whole thing.

**Comment by kdavisk6** [comment]
I see where your head is at now.  When the body is set directly, `RequestTemplate` does not try to do anything to the body.  The Charset is used to encode the URI and Query String parameters, so it should still be ok.

Is the Charset included on the Request `Content-Type` header if set?  I couldn't find anything that does that directly, but it may be the side affect you are experiencing.  If that's the case, I can remove the Charset from the encoding calls and hard-code it to UTF-8, which is probably best.

**Comment by kdavisk6** [comment]
@velo I'm cool with the PR, let's move forward with that.

**Comment by velo** [comment]
Fix merged
